# Dev: MySQL via Dev Services
%dev.quarkus.datasource.db-kind=mysql
%dev.quarkus.datasource.devservices.enabled=true
%dev.quarkus.datasource.devservices.db-name=notification_db
%dev.quarkus.datasource.devservices.username=dbuser
%dev.quarkus.datasource.devservices.password=dbuser
%dev.quarkus.hibernate-orm.schema-management.strategy=drop-and-create

# Prod: H2 In-Memory
%prod.quarkus.datasource.db-kind=h2
%prod.quarkus.datasource.jdbc.url=jdbc:h2:mem:notificationdb
%prod.quarkus.hibernate-orm.database.generation=drop-and-create

quarkus.swagger-ui.always-include=true

quarkus.http.port=8082

# Prod: Kafka-Broker
%prod.kafka.bootstrap.servers=redpanda-1:9092

# Kafka: incoming comment events
mp.messaging.incoming.comment-events.connector=smallrye-kafka
mp.messaging.incoming.comment-events.topic=comment-events
mp.messaging.incoming.comment-events.value.deserializer=ch.hftm.messaging.CommentEventDeserializer
mp.messaging.incoming.comment-events.auto.offset.reset=earliest

# Pre-create topics
quarkus.kafka.devservices.topic-partitions.comment-events=1
