%dev.quarkus.datasource.db-kind=mysql
%dev.quarkus.datasource.devservices.enabled=true
%dev.quarkus.datasource.devservices.db-name=text_processing_db
%dev.quarkus.datasource.devservices.username=dbuser
%dev.quarkus.datasource.devservices.password=dbuser
%dev.quarkus.hibernate-orm.schema-management.strategy=drop-and-create

quarkus.http.port=8081

# Kafka: incoming validation requests
mp.messaging.incoming.validation-request.connector=smallrye-kafka
mp.messaging.incoming.validation-request.topic=text-validation-request
mp.messaging.incoming.validation-request.value.deserializer=ch.hftm.messaging.ValidationRequestDeserializer
mp.messaging.incoming.validation-request.auto.offset.reset=earliest

# Kafka: outgoing validation responses
mp.messaging.outgoing.validation-response.connector=smallrye-kafka
mp.messaging.outgoing.validation-response.topic=text-validation-response
mp.messaging.outgoing.validation-response.value.serializer=io.quarkus.kafka.client.serialization.JsonbSerializer

# Kafka: incoming summary requests
mp.messaging.incoming.summary-request.connector=smallrye-kafka
mp.messaging.incoming.summary-request.topic=summary-request
mp.messaging.incoming.summary-request.value.deserializer=ch.hftm.messaging.SummaryRequestDeserializer
mp.messaging.incoming.summary-request.auto.offset.reset=earliest

# Kafka: outgoing summary responses
mp.messaging.outgoing.summary-response.connector=smallrye-kafka
mp.messaging.outgoing.summary-response.topic=summary-response
mp.messaging.outgoing.summary-response.value.serializer=io.quarkus.kafka.client.serialization.JsonbSerializer

# Pre-create topics
quarkus.kafka.devservices.topic-partitions.text-validation-request=1
quarkus.kafka.devservices.topic-partitions.text-validation-response=1
quarkus.kafka.devservices.topic-partitions.summary-request=1
quarkus.kafka.devservices.topic-partitions.summary-response=1
