%dev.quarkus.datasource.db-kind=mysql
%dev.quarkus.datasource.devservices.enabled=true
%dev.quarkus.datasource.devservices.db-name=blog_nw
%dev.quarkus.datasource.devservices.username=dbuser
%dev.quarkus.datasource.devservices.password=dbuser
%dev.quarkus.hibernate-orm.schema-management.strategy=drop-and-create

# Kafka: outgoing validation requests
mp.messaging.outgoing.validation-request.connector=smallrye-kafka
mp.messaging.outgoing.validation-request.topic=text-validation-request
mp.messaging.outgoing.validation-request.value.serializer=io.quarkus.kafka.client.serialization.JsonbSerializer

# Kafka: incoming validation responses
mp.messaging.incoming.validation-response.connector=smallrye-kafka
mp.messaging.incoming.validation-response.topic=text-validation-response
mp.messaging.incoming.validation-response.value.deserializer=ch.hftm.messaging.ValidationResponseDeserializer
mp.messaging.incoming.validation-response.auto.offset.reset=earliest

# Kafka: outgoing summary requests
mp.messaging.outgoing.summary-request.connector=smallrye-kafka
mp.messaging.outgoing.summary-request.topic=summary-request
mp.messaging.outgoing.summary-request.value.serializer=io.quarkus.kafka.client.serialization.JsonbSerializer

# Kafka: incoming summary responses
mp.messaging.incoming.summary-response.connector=smallrye-kafka
mp.messaging.incoming.summary-response.topic=summary-response
mp.messaging.incoming.summary-response.value.deserializer=ch.hftm.messaging.SummaryResponseDeserializer
mp.messaging.incoming.summary-response.auto.offset.reset=earliest

# Pre-create topics
quarkus.kafka.devservices.topic-partitions.text-validation-request=1
quarkus.kafka.devservices.topic-partitions.text-validation-response=1
quarkus.kafka.devservices.topic-partitions.summary-request=1
quarkus.kafka.devservices.topic-partitions.summary-response=1
